name: Manu CI

on: [push]

jobs:
    build-test:
        name: Build and Test
        runs-on: ubuntu@latest

        steps:
            - name: Checkout repository
            - uses: actions/checkout@v3

            - name: Setup Nodejs
              uses: actions/setup-node@v4
              
            - name: Run init
              run: npm run init

            - name: Run build
              run: npm run build

            - name: Run test
              run: npm run test
            
            - name: Run deploy
              run: npm run deploy

            
